attempt to stabilize tests
ansible/receptor pull request #443
Opened 2021-10-15 04:27 UTC by fosterseth

2021-11-04 13:27 UTC, eqrx requested changes

2021-11-04 13:27 UTC, eqrx commented on pkg/controlsvc/controlsvc.go
> +	logger.Info("Client connected to control service %s\n", conn.RemoteAddr().String())
Could that just be 
`logger.Info("Client connected to control service %v\n", conn.RemoteAddr())`

2021-11-04 13:27 UTC, eqrx commented on pkg/controlsvc/controlsvc.go
> +						if strings.HasSuffix(err.Error(), "normal close") {
where does this "normal close" come from? can this be done with the `errors.Is` method?

2021-11-04 13:27 UTC, eqrx commented on pkg/workceptor/command.go
> +					os.Exit(-1)
https://pkg.go.dev/os#Exit: "For portability, the status code should be in the range [0, 125].". Also os.Exit causes the process to exit immediately without executing any defers and such. Is that desired?

2021-11-04 13:27 UTC, eqrx commented on pkg/workceptor/remote_work.go
> +			_ = conn.(interface{ CloseConnection() error }).CloseConnection()
Maybe make that a named interface instead of an anonymous one?

2021-11-04 13:27 UTC, eqrx commented on pkg/workceptor/remote_work.go
> +			_ = conn.(interface{ CloseConnection() error }).CloseConnection()
See above

2021-11-04 13:27 UTC, eqrx commented on pkg/workceptor/workceptor.go
> +		statChan := make(chan struct{}, 1)
No need to buffer and send empty structs and sent empty structs into it. Just close the channel at the sender and the receiver will unblock

2021-11-04 13:27 UTC, eqrx commented on tests/functional/mesh/work_test.go
> +	// defer m.WaitForShutdown()
Why is that all commented out? Could you add a comment describing why this is done?

2021-11-16 17:09 UTC, fosterseth commented
closing in favor of https://github.com/ansible/receptor/pull/487

2021-11-16 17:09 UTC, closed without merging