Upload binary to S3 instead of archiving with Actions
ansible/receptor pull request #465
Opened 2021-11-03 20:17 UTC by shanemcd

2021-11-04 13:16 UTC, eqrx requested changes
This will break all actions running on forks, could you split this workflow into push and pull_request triggered ones?

2021-11-04 13:31 UTC, eqrx requested changes

2021-11-04 13:31 UTC, eqrx commented on .github/workflows/pull_request.yml
> +            -a "bucket=receptor-nightlies object=PRs/${{github.event.number}}/receptor src=./receptor mode=put"
Doesn't this also allow any github user to upload arbitrary source code to be build by actions and uploaded into the bucket?

2021-11-16 22:50 UTC, fosterseth commented
we have this solution instead https://github.com/ansible/receptor/pull/466
probably can close this PR

2021-11-17 11:56 UTC, closed without merging