k8s skip stdin if stdin file is 0 bytes
ansible/receptor pull request #549
Opened 2022-02-15 23:42 UTC by fosterseth

related https://github.com/ansible/receptor/issues/489

Check if stdin file is 0 bytes. If empty, do not attempt to attach stdin stream to container. If the container already exited, this can lead to an unintended error.

2022-02-16 00:06 UTC, fosterseth commented
to test this I simulated the error by adding a sleep(3) right before the code to attach the stdin stream. That way the container was certainly done by this point. Without patch, I got the error, although a slightly different message than in https://github.com/ansible/receptor/issues/489

```
    "Q1ojiukD": {
        "Detail": "Stream error running pod: unable to upgrade connection: container worker not found in pod kubeit2-ffp5x_default",
```

It may just be the case that the test is hitting the problem when the pod is in a particular state, that I am not exactly capturing here.

My patch makes these pods and work units pass as expected.

2022-02-16 00:13 UTC, fosterseth commented on pkg/workceptor/kubernetes.go
> +func podRunningAndReady() func(event watch.Event) (bool, error) {
all of this is linter shenanigans

2022-02-16 21:57 UTC, eqrx commented on pkg/workceptor/stdio_utils.go
> +var errFileSizeZero error
That is nil. Use errors.New to create an error.

2022-02-16 21:59 UTC, eqrx commented on pkg/workceptor/kubernetes.go
> +		if err == errFileSizeZero {
Use errors.Is to compare errors or create a custom error type

2022-02-16 22:06 UTC, eqrx requested changes

2022-02-16 22:06 UTC, eqrx commented on pkg/workceptor/kubernetes.go
> +		if err == errFileSizeZero {
Use errors.Is to compare errors or create a custom error type

2022-02-16 22:06 UTC, eqrx commented on pkg/workceptor/stdio_utils.go
> +var errFileSizeZero error
That is nil. Use errors.New to create an error.

2022-02-22 00:20 UTC, shanemcd commented
I included this commit + the PR feedback in https://github.com/ansible/receptor/pull/547

2022-02-22 00:20 UTC, closed without merging