Detect OCP version to determine reconnect support
ansible/receptor pull request #693
Opened 2022-11-29 22:52 UTC by fosterseth

followup to https://github.com/ansible/receptor/pull/683

It doesn't suffice to check K8S server version if running on OpenShift, as the K8S versions reported don't align with upstream.

Therefore, we should try to first detect the OCP server version, and use that to determine if reconnect support should be used.

2022-11-29 22:52 UTC, fosterseth commented on .golangci.yml
> -    - ifshort
these are deprecated, removing.

2022-11-30 18:19 UTC, TheRealHaoLiu commented on pkg/workceptor/kubernetes.go
> +		compatibleVer = "v4.10.44"
4.10.42

2022-12-01 11:43 UTC, gundalow commented on pkg/workceptor/kubernetes_test.go
> +	tests := []args{
I'm a lot happier now we have these version checks in. Thank you.

2022-12-01 13:08 UTC, shanemcd commented on .golangci.yml
> -    - deadcode
Please open a one-of PR for these changes that we will merge before this PR.

2022-12-01 13:10 UTC, shanemcd requested changes
Nice work.

Before we merge this:

- Move linter changes out into a separate PR (preferably), or at least another commit.
- I don't think the changes to go.mod and go.sum are necessary. If anything they seem dangerous. Unless there was a specific reason for doing that, please revert the changes to those files.

2022-12-01 15:51 UTC, TheRealHaoLiu commented
this will require us to give the awx serviceaccount permission to get clusteroperator resource

2022-12-01 21:36 UTC, TheRealHaoLiu commented
we decided to not do this and ask user to add 
```
  ee_extra_env: |
    - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
      value: enabled
 ```
 
 in awx spec

2023-02-08 01:05 UTC, fosterseth commented
not the direction we wish to go

2023-02-08 01:05 UTC, closed without merging